# @diegotorres50: import routes from a controller directory
qualisoft_app:
    resource: "@QualisoftAppBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
