# @diegotorres50: import routes from a controller directory
qualisoft_app:
    resource: "@QualisoftAppBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# @diegotorres50: usamos FOSJsRoutingBundle para generar URLs desde JS
# fos_js_routing:
#     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
